scriptieshop/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.urls import path, re_path, include
from django.http import HttpResponse, HttpResponseForbidden
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .models import Order
from .views import *

admin.site.site_header = settings.PROJECT_NAME.capitalize()
admin.site.site_title = settings.PROJECT_NAME.capitalize()
admin.site.enable_nav_sidebar = False

def forget(request, pk):
    pks = request.session.get('pks', [])
    if int(pk) in pks:
        pks.remove(int(pk))
        request.session['pks'] = pks
    return redirect('/cart/')

def topsecret(request):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    filename = request.path.split('/')[-1]
    response = HttpResponse()
    response['Content-Type'] = ''
    response['X-Accel-Redirect'] = f'/topsecret/{filename}' # nginx internal location
    return response

urlpatterns = staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', RedirectView.as_view(url='/accounts/login/')),
    path('logout/', RedirectView.as_view(url='/accounts/logout/')),
    path('bindprice/', BindPrice.as_view(), name='bindprice'),
    path('bwprice/', BWPriceCurve.as_view(), name='bwprice'),
    path('fcprice/', ColorPriceCurve.as_view(), name='fcprice'),
    path('opdracht/<int:pk>/', Worksheet.as_view(), name='worksheet'),
    path('cancel/<int:pk>/', forget, name='forget'),
    re_path('download/', topsecret, name='download'),
    path('mollie-webhook/', webhook, name='webhook'),
    path('', include('cms.urls', namespace='cms')),
]

scriptieshop/models.py
import os, math

from django.db import models
from django.conf import settings
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.core.files.storage import FileSystemStorage

from cms.decorators import page_model, section_model
from cms.models import BasePage, BaseSection
from cms.fields import CharField

from .count import count_file

@page_model
class Page(BasePage):
    pass

@section_model
class Section(BaseSection):
    page = models.ForeignKey(Page, related_name='sections', on_delete=models.PROTECT)

class Variable(models.Model):
    TYPES = [
        (10, 'Laag BTW tarief'),
        (11, 'Hoog BTW tarief'),
        (12, 'Verzendkosten'),
        (20, 'Winstfactor zwart/wit'),
        (21, 'Beginprijs zwart/wit'),
        (22, 'Eindprijs zwart/wit'),
        (23, 'Maximummprijs zwart/wit'),
        (24, 'Minimumprijs zwart/wit'),
        (30, 'Winstfactor kleur'),
        (31, 'Beginprijs kleur'),
        (32, 'Eindprijs kleur'),
        (33, 'Maximumprijs kleur'),
        (34, 'Minimumprijs kleur'),
        (40, 'Lijmband basisprijs'),
        (41, 'Lijmband prijs per vel'),
        (50, 'Metalen ring basisprijs'),
        (51, 'Metalen ring prijs per vel'),
        (60, 'Plastic ring basisprijs'),
        (61, 'Plastic ring prijs per vel'),
    ]

    variable = models.PositiveIntegerField('variabele', choices=TYPES, unique=True)
    value = models.PositiveIntegerField('waarde', default=0)

    def __str__(self):
        return str(self.value)

    class Meta:
        verbose_name = 'variabele'
        verbose_name_plural = 'variabelen'
        ordering = ['variable']

ORDER_STATUSES = (
    # These are equal to the statuses that Mollie returns:
    ('open', 'nog niet betaald'),
    ('canceled', 'betaling geannuleerd'),
    ('expired', 'betaling verlopen'),
    ('failed', 'betaling mislukt'),
    ('paid', 'betaald'),
)

class Order(models.Model):
    SHIPPING = (
        (False, 'Afhalen'),
        (True, 'Verzenden'),
    )
    shipping = models.BooleanField('verzendwijze', choices=SHIPPING, default=False)
    customer = CharField('naam')
    email = models.EmailField('e-mail')
    address = models.TextField('adres')
    phone = CharField('telefoonnummer')
    notes = models.TextField('opmerkingen', blank=True)

    total = models.DecimalField('totaalbedrag', max_digits=8, decimal_places=2)
    status = models.CharField('status', max_length=32, choices=ORDER_STATUSES, default=ORDER_STATUSES[0][0])
    created = models.DateTimeField('aangemaakt', auto_now_add=True)
    updated = models.DateTimeField('gewijzigd', auto_now=True)

    assignee = CharField('in behandeling door', blank=True)

    def __str__(self):
        return self.get_order_nr()

    def get_order_nr(self):
        year = self.created.year
        return f'S{year}{self.id:04d}'
    get_order_nr.short_description = 'order nr.'

    def get_description(self):
        return 'Bestelling met nummer ' + self.get_order_nr()

    class Meta:
        ordering = ['-created']
        verbose_name = 'bestelling'
        verbose_name_plural = 'bestellingen'

class Print(models.Model):
    COLOR = (
        (1, 'Automatisch'),
        (2, 'Zwart/Wit'),
    )

    DUPLEX = (
        (False, 'Enkelzijdig'),
        (True, 'Dubbelzijdig'),
    )

    BINDINGS = (
        (1, 'Lijmband'),
        (2, 'Metalen Ring'),
        # (3, 'Plastic Ring'),
    )

    PAPERTYPES = (
        (10, '80 g/m² Navigator'),
        (20, '100 g/m² Color Copy'),
        (30, '120 g/m² Text & Graphics'),
    )

    FRONT_COVERS = (
        (10, 'Transparant mat plastic'),
        (20, 'Transparant glossy plastic'),
        (50, '300 g/m² wit papier met bedrukking'),
    )

    BACK_COVERS = (
        (10, 'Transparant mat plastic'),
        (20, 'Transparant glossy plastic'),
        (30, 'Zwart plastic'),
        (40, 'Wit plastic'),
        (50, '300 g/m² wit papier'),
    )

    order = models.ForeignKey(Order,
                              related_name='prints',
                              blank=True, null=True,
                              on_delete=models.CASCADE)
    safe_storage = FileSystemStorage(location=settings.SAFE_ROOT)
    file = models.FileField('PDF bestand', storage=safe_storage, blank=True)
    original_filename = models.CharField(max_length=255, blank=True)
    calculated = models.BooleanField(default=False)
    bw_pages = models.PositiveIntegerField('aantal zijdes z/w', default=0)
    fc_pages = models.PositiveIntegerField('aantal zijdes kleur', default=0)
    pages = models.PositiveIntegerField('aantal zijdes', default=0)
    sheets = models.PositiveIntegerField('aantal velletjes', default=0)
    amount = models.PositiveIntegerField('aantal exemplaren', default=1, validators=[MinValueValidator(1)])
    color = models.PositiveIntegerField('kleur', default=1, choices=COLOR)
    duplex = models.BooleanField('duplex', choices=DUPLEX, default=False)
    papertype = models.PositiveIntegerField('papiersoort', choices=PAPERTYPES, default=10)
    front_cover = models.PositiveIntegerField('voorkaft', choices=FRONT_COVERS, default=10)
    back_cover = models.PositiveIntegerField('achterkaft', choices=BACK_COVERS, default=30)
    binding = models.PositiveIntegerField('inbinden', choices=BINDINGS, default=1)
    created = models.DateTimeField('aangemaakt', auto_now_add=True)
    updated = models.DateTimeField('gewijzigd', auto_now=True)

    def __str__(self):
        if self.file:
            return self.original_filename
        return "Scriptie"

    def count_pages(self):
        if self.file and not self.calculated:
            filename = os.path.join(settings.SAFE_ROOT, self.file.name)
            self.bw_pages, self.fc_pages = count_file(filename)
            self.calculated = True

        if self.color == 2:
            self.bw_pages += self.fc_pages
            self.fc_pages = 0

        self.pages = self.bw_pages + self.fc_pages

        if self.duplex:
            self.sheets = math.ceil(self.pages / 2)
        else:
            self.sheets = self.pages

        self.save()
        return self.pages

    class Meta:
        ordering = ['-created']
        verbose_name = 'printopdracht'
        verbose_name_plural = 'printopdrachten'

scriptieshop/views.py
import logging

from django.conf import settings
from django.http import HttpResponse
from django.core.mail import EmailMessage
from django.shortcuts import redirect, reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView, DetailView
from django.core.exceptions import SuspiciousOperation
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.decorators.http import require_http_methods

from mollie.api.client import Client
from cms.forms import ContactForm
from cms.decorators import section_view
from cms.views import SectionView, SectionFormView

from .utils import *
from .models import *
from .forms import *

logger = logging.getLogger('django.request')
mollie_client = Client()
mollie_client.set_api_key(settings.MOLLIE_API_KEY)

@csrf_exempt
@require_http_methods(['POST'])
def webhook(request):
    try:
        payment_id = request.POST.get('id')
        payment = mollie_client.payments.get(payment_id)
        order_id = payment.metadata['order_id']
        order = Order.objects.get(id=order_id)
        if order.status == payment.status or order.status == 'paid':
            raise SuspiciousOperation(
                f'Something weird happened:'
                f'Mollie called the webhook with status = "{payment.status}"'
                f'but the order status is already "{order.status}"')
        order.status = payment.status
        order.save()
        if order.status == 'paid':
            send_email(order)

    except Exception:
        import traceback
        logger.error(traceback.format_exc())

    # Always return successfully, as to not leak information
    return HttpResponse()

def get_payment_url(order):
    amount = {
        'currency': 'EUR',
        'value': f'{order.total:.2f}',
        }
    description = order.get_description()
    webhookUrl = settings.CANONICAL_URL + reverse('webhook')
    redirectUrl = settings.CANONICAL_URL + '/betaald/'
    metadata = {'order_id': str(order.id)}
    payment = mollie_client.payments.create({
        'amount': amount,
        'description': description,
        'webhookUrl': webhookUrl,
        'redirectUrl': redirectUrl,
        'metadata': metadata,
    })
    return payment.checkout_url

def send_email(order):
    body = f'''Beste Copyshoppers,

Iemand heeft een opdracht geplaatst op Scriptieshop.nl. De betaling
met iDeal is geslaagd. Dat betekent dat we nu zo snel mogelijk aan de
slag moeten om deze bestelling te printen en te versturen!

Je kunt de details van deze bestelling bekijken op de opdrachtbon:
https://www.scriptieshop.nl/opdracht/{order.pk}/
Hier kun je ook de benodigde bestanden downloaden.

Als je contact op wilt nemen met de besteller kan dat door simpelweg
op deze email te antwoorden. Het Reply-To adres is ingesteld op
{order.email}.

Vergeet niet deze tekst te verwijderen uit je antwoord :-)

Groeten,
De server op Scriptieshop.nl
'''
    email = EmailMessage(
        to=settings.DEFAULT_TO_EMAIL,
        from_email=settings.DEFAULT_FROM_EMAIL,
        body=body,
        subject=order.get_description(),
        headers={'Reply-To': order.email},
    )
    email.send()

@section_view
class Text(SectionView):
    verbose_name = 'Tekst'
    fields = ['content']
    template_name = 'text.html'

@section_view
class Image(SectionView):
    verbose_name = 'Afbeelding'
    fields = ['image']
    template_name = 'image.html'

@section_view
class Steps(SectionView):
    verbose_name = 'Stappenplan'
    fields = ['content']
    template_name = 'steps.html'

@section_view
class Upload(SectionFormView):
    verbose_name = 'Upload'
    fields = ['title']
    template_name = 'upload.html'
    form_class = UploadForm

    def form_valid(self, form):
        p = form.save()
        pks = self.request.session.get('pks', [])
        if p.pk not in pks:
            pks.append(p.pk)
        self.request.session['pks'] = pks
        return redirect('/cart/')

@section_view
class Cart(SectionFormView):
    verbose_name = 'Winkelwagentje'
    fields = ['content', 'href']
    template_name = 'cart.html'
    form_class = CartForm

    def get_form_kwargs(self):
        pks = self.request.session.get('pks', [])
        self.prints = Print.objects.filter(pk__in=pks)
        return {'prints': self.prints}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['invalid'] = not self.prints or not all([p.file for p in self.prints])
        context['vat'] = get_variable(10).value
        return context

    def form_valid(self, form):
        pks = self.request.session.get('pks', [])
        p = form.save()
        if p.pk not in pks:
            pks.append(p.pk)
        self.request.session['pks'] = pks
        return redirect('/cart/')

@section_view
class Checkout(SectionFormView):
    verbose_name = 'Bestellen'
    fields = ['content']
    template_name = 'checkout.html'
    form_class = CheckoutForm

    def get_form_kwargs(self):
        pks = self.request.session.get('pks', [])
        self.prints = Print.objects.filter(pk__in=pks)
        return {'prints': self.prints}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pks = self.request.session.get('pks', [])
        context['shipping_costs'] = get_variable(12).value / 100
        context['prints'] = Print.objects.filter(pk__in=pks).exclude(file='')
        context['cart'] = calculate_cart(context['prints'])
        return context

    def form_valid(self, form):
        order = form.save()
        self.request.session['pks'] = []
        if settings.DEBUG:
            send_email(order)
            return redirect('/betaald/')
        if order.status == 'paid':
            return redirect('/betaald/')
        payment_url = get_payment_url(order)
        return redirect(payment_url)

@section_view
class Contact(SectionFormView):
    verbose_name = 'Contact'
    fields = []
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = '/thanks/'


###############################################################################


class Worksheet(UserPassesTestMixin, DetailView):
    template_name = 'worksheet.html'
    model = Order

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['prints'] = self.object.prints.all()
        return context

class BindPrice(UserPassesTestMixin, FormView):
    form_class = BindPriceForm
    template_name = 'bindprice.html'

    def test_func(self):
        return self.request.user.has_perm('shop_variable_change')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'initial': self.get_variables()})
        return kwargs

    def get_variables(self):
        return {
            'glue1': get_variable(40),
            'glue2': get_variable(41),
            'metal1': get_variable(50),
            'metal2': get_variable(51),
            'plastic1': get_variable(60),
            'plastic2': get_variable(61),
            'vat': get_variable(10),
        }

    def form_valid(self, form):
        form.save(self.get_variables())
        return redirect('/cart/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_variables())
        return context

class PriceCurve(UserPassesTestMixin, FormView):
    form_class = PriceCurveForm
    template_name = 'pricecurve.html'

    def test_func(self):
        return self.request.user.has_perm('shop_variable_change')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'initial': self.get_variables()})
        return kwargs

    def form_valid(self, form):
        form.save(self.get_variables())
        return redirect('/cart/')

class BWPriceCurve(PriceCurve):
    def get_variables(self):
        return {
            'factor': get_variable(20),
            'begin': get_variable(21),
            'end': get_variable(22),
            'maximum': get_variable(23),
            'minimum': get_variable(24),
            'vat': get_variable(10),
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_variables())
        context['include_legacy_bw'] = True
        return context

class ColorPriceCurve(PriceCurve):
    def get_variables(self):
        return {
            'factor': get_variable(30),
            'begin': get_variable(31),
            'end': get_variable(32),
            'maximum': get_variable(33),
            'minimum': get_variable(34),
            'vat': get_variable(10),
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_variables())
        context['include_legacy_fc'] = True
        return context

scriptieshop/templates/cart.html
{% load static cms %}

<section class="cart" id="cart">
  <div class="wrapper">
    <center>
      {% eval section.content %}
    </center>

    <form method="post" class="cart" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="hidden" name="section" value="{{section.pk}}">
      {{form.formset.management_form}}

      {% if form.formset.errors %}
        <div class="global_error">
          Oeps! Er is iets misgegaan bij het opslaan. Herstel a.u.b. de onderstaande fouten en probeer het opnieuw.
        </div>
      {% endif %}

      {% for form in form.formset %}
        {% for field in form.hidden_fields %}{{field}}{% endfor %}
        <div class="print">
          <h2>
            {{form.print.price.amount}} x {{form.print}}
          </h2>

          {% if form.instance.count_pages %}
            {% if not form.print.file %}
              {% include 'cms/formfield.html' with field=form.file %}
              <div class="spacer"></div>
            {% endif %}

            {% for item in form.print.price.items %}
              {% if item.subsubtotal > 0 %}{{item.amount}} x {% endif %}{{item.description|safe}} <span>{{item.subsubtotal|floatformat:2}}</span><br>
            {% endfor %}

            <label class="toggle" for="toggle{{forloop.counter}}">bewerken</label> -
            <label class="toggle"><a href="{% url 'forget' form.print.pk %}">verwijderen</a></label>
            <input type="checkbox" class="toggle" id="toggle{{forloop.counter}}">
            <div class="collapse">
              {% include 'cms/formfield.html' with field=form.duplex %}
              {% include 'cms/formfield.html' with field=form.papertype %}
              {% include 'cms/formfield.html' with field=form.binding %}
              {% include 'cms/formfield.html' with field=form.front_cover %}
              {% include 'cms/formfield.html' with field=form.back_cover %}
            </div>
            {% include 'cms/formfield.html' with field=form.amount %}
            <div class="subtotal">Subtotaal: €{{form.print.price.subtotal|floatformat:"2"}}</div>
          {% else %}
            <div hidden style="display:none">
              {% include 'cms/formfield.html' with field=form.duplex %}
              {% include 'cms/formfield.html' with field=form.papertype %}
              {% include 'cms/formfield.html' with field=form.binding %}
              {% include 'cms/formfield.html' with field=form.front_cover %}
              {% include 'cms/formfield.html' with field=form.back_cover %}
              {% include 'cms/formfield.html' with field=form.amount %}
            </div>
            <div class="global_error">
              Oeps! Het bestand dat je hebt gestuurd is geen geldig PDF bestand :(
            </div>
            <label class="toggle"><a href="{% url 'forget' form.print.pk %}">verwijderen</a></label>
          {% endif %}
        </div>
      {% endfor %}

      <div class="add">
        <label class="toggle" for="add"><img src="{% static 'plus.svg' %}" width="23"> Document toevoegen</label>
        <input type="checkbox" class="toggle" id="add">
        <div class="collapse addform">
          {% for error in form.non_field_errors %}
            <p style="color:red; margin-top:0">{{error}}</p>
          {% endfor %}
          {% include 'cms/formfield.html' with field=form.bw_pages %}
          {% include 'cms/formfield.html' with field=form.fc_pages %}
          {% include 'cms/formfield.html' with field=form.file %}
          {% include 'cms/formfield.html' with field=form.duplex %}
          {% include 'cms/formfield.html' with field=form.papertype %}
          {% include 'cms/formfield.html' with field=form.binding %}
          {% include 'cms/formfield.html' with field=form.front_cover %}
          {% include 'cms/formfield.html' with field=form.back_cover %}
          <div class="spacer"></div>
          <button class="button">Toevoegen</button>
          <div class="spacer"></div>
        </div>
      </div>

      <div class="total">Totaal <small>(inclusief {{vat}}% btw)</small>: €{{form.total|floatformat:"2"}}</div>
      <div class="spacer"></div>
      <div class="spacer"></div>

      <div class="button">
        <a href="{{section.href}}" {% if invalid %}class="invalid" onclick="return false"{% endif %}>Bestellen!</a>
      </div>

      {% if invalid %}
        <div style="max-width: 400px; margin: auto; text-align: center">
          Zorg dat je bij elk document hierboven een PDF bestand upload. Daarna kun je bestellen!
        </div>
      {% endif %}

    </form>


    <div class="spacer"></div>
    {% if perms.scriptieshop.change_variable %}
      <div class="edit">
        <a class="edit" href="{% url 'admin:scriptieshop_variable_change' 18 %}">verzendkosten</a>
        <a class="edit" href="{% url 'bwprice' %}">zwart/witprijzen</a>
        <a class="edit" href="{% url 'fcprice' %}">kleurenprijzen</a>
        <a class="edit" href="{% url 'bindprice' %}">inbindprijzen</a>
      </div>
    {% endif %}
    <div class="spacer"></div>

    {% editsection '<img src="/static/cms/edit.png">' %}
  </div>
</section>
<script>
  for (let widget of document.querySelectorAll('div.print input[type=file], div.print select')) {
      widget.addEventListener('input', function() {
          this.form.submit();
      });
  }
</script>

scriptieshop/templates/checkout.html
{% load cms %}

<section class="checkout">
  <div class="wrapper">
    {% eval section.content %}

    {% if prints %}
      <div class="prints">
        {% for print in prints %}
          <div class="print">
            <h3>{{print.amount}}x {{print}}<br>
              <small>({{print.get_duplex_display|lower}}, ingebonden met {{print.get_binding_display|lower}}, voorkaft {{print.get_front_cover_display|lower}}, achterkaft {{print.get_back_cover_display|lower}})</small>
            </h3>
          </div>
        {% endfor %}

        <form method="post" novalidate>
          {% csrf_token %}

          <div class="shipping">
            <label><input type="radio" name="shipping" value="False" required checked>Afhalen op onze vestiging in Den Bosch</label>
            <label><input type="radio" name="shipping" value="True" required >Verzenden (+ €{{shipping_costs|floatformat:"2"}})</label>
          </div>
          <div class="total">Totaalbedrag: €{{cart.total|floatformat:"2"}}</div>

          {% include 'cms/formfield.html' with field=form.customer %}
          {% include 'cms/formfield.html' with field=form.email %}
          {% include 'cms/formfield.html' with field=form.address %}
          {% include 'cms/formfield.html' with field=form.phone %}
          {% include 'cms/formfield.html' with field=form.notes %}

          <div class="spacer"></div>
          <button class="button" name="section" value="{{section.pk}}">Bevestig deze bestelling</button>

          <p>Door deze bestelling te bevestigen ga je akkoord met onze <a href="/voorwaarden/">Algemene Voorwaarden</a></p>
        </form>
      </div>
    {% endif %}

    {% editsection '<img src="/static/cms/edit.png">' %}
  </div>
</section>

scriptieshop/templates/contact.html
{% load cms %}

<section class="contact">
  <div class="wrapper">
    <div class="title">
      <h1>{{section.title}}</h1>
    </div>

    <div class="form">
      <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
          {% include 'cms/formfield.html' with field=field %}
        {% endfor %}
        <div class="spacer"></div>
        <button class="button" name="section" value="{{section.pk}}">Verstuur</button>
      </form>
    </div>

    {% editsection '<img src="/static/cms/edit.png">' %}
  </div>
</section>

scriptieshop/templates/image.html
{% load cms thumbnail %}

<section class="image">
  <div class="wrapper">
    {% if section.image %}
      <div class="image">
        <img alt="{{section.title}}" src="{% thumbnail section.image 800x800 %}">
      </div>
    {% endif %}

    {% editsection '<img src="/static/cms/edit.png">' %}
  </div>
</section>

scriptieshop/templates/steps.html
{% load cms static %}

<section class="steps">
  <div class="wrapper">
    {% eval section.content %}

    <div class="spacer"></div>

    <h1>{{section.title}}</h1>

    <div class="steps">
      <div>
        <img src="{% static 'upload.svg' %}">
        <h2>1. Bereken wat <br> het kost</h2>
      </div>
      <div>
        <img src="{% static 'print.svg' %}">
        <h2>2. Plaats je bestelling</h2>
      </div>
      <div>
        <img src="{% static 'deliver.svg' %}">
        <h2>3. Bezorgen of afhalen</h2>
      </div>
    </div>

    {% editsection '<img src="/static/cms/edit.png">' %}
  </div>
</section>

scriptieshop/templates/text.html
{% load cms %}

<section class="text">
  <div class="wrapper">
    <div class="title">
      <h1>
        {{section.title}}
      </h1>
    </div>

    <div class="content">
      {% eval section.content %}
    </div>

    {% editsection '<img src="/static/cms/edit.png">' %}
  </div>
</section>

scriptieshop/templates/worksheet.html
{% load static %}

<!doctype html>
<html>
  <head>
    <title>{% block title %}Scriptieshop.nl{% endblock %}</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'main10.scss.css' %}">
    <link rel="icon" href="{% static 'favicon.png' %}">
    {% block extrahead %}{% endblock %}
  </head>
  <body class="worksheet">

    <header>
      <a href="{% url 'admin:scriptieshop_order_changelist' %}"><img src="{% static 'logo.svg' %}" alt="Scriptieshop.nl"></a>
    </header>

    {% block content %}
      <section class="worksheet">
        <div class="wrapper">
          <div class="details">
            <dl>
              <dt>Datum:</dt>
              <dd>{{order.created}}</dd>

              <dt>Naam:</dt>
              <dd>{{order.customer}}</dd>

              <dt>Adres:</dt>
              <dd>{{order.address}}</dd>

              <dt>Levering:</dt>
              <dd>{{order.get_shipping_display}}</dd>
            </dl>
            <dl>
              <dt>Telefoon:</dt>
              <dd>{{order.phone}}</dd>

              <dt>Email:</dt>
              <dd>{{order.email}}</dd>

              <dt>Totaalbedrag:</dt>
              <dd>{{order.total}}</dd>

              <dt>Status:</dt>
              <dd>{{order.get_status_display}}</dd>
            </dl>
          </div>
        </div>
      </section>

      <div class="wrapper masonry">
        <div>
          <section style="height:100%">
            <h2>Bestelling</h2>
            {% for print in prints %}
              <div class="paper" style="background:white">
                <h3><span>{{print.amount}}x</span> <a href="{% url 'download' %}{{print.file.name}}">{{print}}</a></h3>
                {{print.get_duplex_display}}<br>
                {{print.get_papertype_display}}<br>
                Inbinden met {{print.get_binding_display}}<br>
                Voorkaft: {{print.get_front_cover_display}}<br>
                Achterkaft: {{print.get_back_cover_display}}<br>
              </div>
            {% endfor %}
          </section>
        </div>

        <div>
          <section>
            <h2>Opmerking</h2>
            <div class="paper" style="min-height: 100px; background:white">
              {{object.notes}}
            </div>
          </section>

          <section>
            <h2>Notities</h2>
            <div class="paper" style="min-height: 200px">
            </div>
          </section>
        </div>
      </div>
    {% endblock %}

  </body>
</html>